config/routes.rb
Rails.application.routes.draw do
  get 'gps', to: 'test#index', as: 'gps'
  controller :tasks do
    post 'tasks/:id' => :answer
  end
  resources :tasks

  controller :games do
    get 'games' => :index
    post 'games' => :show
    get '/games/:id', to: 'games#end', as: 'gameend'
  end
  resources :done_tasks

  resources :done_games
  resources :sessions
  root 'welcome#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :game
  has_many :done_tasks, dependent: :destroy, :foreign_key => :task_id

  def next
    game.tasks.where("id > ?", id).order("id ASC").first
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :answer]

  def show
    case @task.tp
      when 2
        render 'gps'
      when 1
        render 'text'
    end
  end

  def answer
    if @task.tp ==1
      answ = params[:answ]
      if answ == @task.check
        @done_task.result=1
        @done_task.endtime =DateTime.now
        @done_task.points=@task.points
        @done_task.save
        if (@task.last)
          redirect_to gameend_path(@task.game)
        else
          redirect_to @task.next, notice: "Dobrze, a teraz kolejne zadanie"

        end
      else
        redirect_to @task, alert: "Zle, sprobuj ponownie"
      end
    else
      @done_task.result=1
      @done_task.endtime =DateTime.now
      @done_task.points=@task.points
      @done_task.save
      if (@task.last)
        redirect_to gameend_path(@task.game)
      else
        redirect_to @task.next, notice: "Dobrze, a teraz kolejne zadanie"
      end
    end

  end


private
def get_done_task
  @done_task = DoneTask.find(session[:dtsk])
  if (@done_task.task_id!=@task.id)
    @done_task = DoneTask.create(:donegame_id => @done_game.id, :task_id => @task.id, :session_id => @sess.id)
    session[:dtsk]=@done_task.id
  end
rescue ActiveRecord::RecordNotFound
  @done_task = DoneTask.create(:donegame_id => @done_game.id, :task_id => @task.id, :session_id => @sess.id)
  session[:dtsk]=@done_task.id
end

def get_done_game
  @done_game = DoneGame.find(session[:dgm])
rescue ActiveRecord::RecordNotFound
  @done_game = DoneGame.create(:game_id => @task.game.id, :session_id => @sess.id)
  session[:dgm]=@done_game.id
end

def get_session_params

  @sess = Session.find(session[:ses])
  return true
rescue ActiveRecord::RecordNotFound
  redirect_to '', alert: "Musisz sie zalogowac"
  return false
end

def set_task
  @task = Task.find(params[:id])
  r = get_session_params
  get_done_game if r
  get_done_task if r
end

def task_params
  params.require(:task).permit(:game_id, :title, :content, :type, :latitude, :longitude, :check, :last, :answ)
end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.number_field :type %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :check %><br>
    <%= f.text_field :check %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.check_box :last %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/gps.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<div>
  <%= raw @task.content %>
</div>
<%= hidden_field_tag 'targetLong', @task.longitude %>
<%= hidden_field_tag 'targetLat' ,@task.latitude%>
<div class="compasDiv">
  <table id='compas' class="reslutTable">
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>N</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>
        <div class="arrow arrow-left-up">&nbsp;</div>
      </td>
      <td class="arrow arrow-up">&nbsp;</td>
      <td>
        <div class="arrow arrow-right-up">&nbsp;</div>
      </td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>E</td>
      <td class="arrow arrow-left">&nbsp;</td>
      <td id="dstance">12m</td>
      <td class="arrow arrow-right">&nbsp;</td>
      <td>W</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>
        <div class="arrow arrow-left-down">&nbsp;</div>
      </td>
      <td class="arrow arrow-down">&nbsp;</td>
      <td>
        <div class="arrow arrow-right-down">&nbsp;</div>
      </td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>S</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
  <div>
    <%= form_tag '', :method => 'post' do %>
        <%= hidden_field_tag 'lgt' %>
        <%= hidden_field_tag 'log' %>
        <%= hidden_field_tag 'acr' %>
        <%= submit_tag "Odpowiedz", disabled:true, id: 'sbmt' %>
    <% end %>
  </div>
  <script>gpsSupport()</script>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Title</th>
      <th>Content</th>
      <th>Type</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Check</th>
      <th>Last</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.game.desc %></td>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.tp %></td>
        <td><%= task.latitude %></td>
        <td><%= task.longitude %></td>
        <td><%= task.check %></td>
        <td><%= task.last %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Type:</strong>
  <%= @task.tp %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @task.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @task.longitude %>
</p>

<p>
  <strong>Check:</strong>
  <%= @task.check %>
</p>

<p>
  <strong>Last:</strong>
  <%= @task.last %>
</p>
<% if @task.last  %>
    <%= link_to 'Następne', gameend_path(@task.game) %>
<% else%>
    <%= link_to 'Następne', @task.next %>
<% end %>

app/views/tasks/text.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<p>
  <h1>
  <%= @task.title %>
  </h1>
</p>
<div>
  <%= raw @task.content %>
</div>

<%= form_tag '', :method => 'post' do %>
<%= text_field_tag 'answ' %>
<%= submit_tag "Odpowiedz", id: 'sbmt' %>
<% end %>