config/routes.rb
Rails.application.routes.draw do
  get 'gps', to: 'test#index', as: 'gps'
  controller :tasks do
    post 'tasks/:id' => :answer
  end
  resources :tasks

  controller :games do
    get 'games' => :index
    post 'games' => :show
    get '/games/:id', to: 'games#end', as: 'gameend'
  end
  resources :done_tasks

  resources :done_games
  resources :sessions
  root 'welcome#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :done_games, dependent: :destroy
  has_many :tasks, dependent: :destroy
  attr_accessor :distance
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def end
    @done_game = DoneGame.find(session[:dgm])
    @done_game.result=1
    @done_game.endtime =DateTime.now
    @done_game.save
    @tsks = @done_game.done_tasks
  end

  def show
    # session.delete(:dgm)
    create_session params[:nick]
    @games = Game.all
    currentLongitude = params[:log].to_i
    currentLatitude = params[:lgt].to_i
    @games.each do |g|
      task = g.tasks.first
      distance = getDistance(currentLongitude, currentLatitude, task.longitude, task.latitude)
      g.distance = distance
    end
    @games = @games.to_a
    @games.sort! { |a, b| a.distance <=> b.distance }
  end

  private
  def create_session(nick)
    @session = Session.create(:name => nick.to_s, :browser => request.user_agent.to_s, :ip => request.ip, :tp => 1)
    session[:ses]=@session.id
  end

  def game_params
    params.permit(:lgt, :log, :acr, :nick)
  end

  def getDistance(currentLg, currentLt, targetLg, targetLt)
    r = 6371;
    dLat = (currentLt - targetLt) * Math::PI / 180
    dLon = (currentLg - targetLg)* Math::PI / 180
    a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.cos(targetLt * Math::PI / 180) * Math.cos(currentLt * Math::PI / 180) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    d = r * c;
    return d;
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/end.html.erb
<h1>
Gratuluje zakończyłeś gre z wynikiem:<%= @tsks.sum(:points)%>
</h1>
<table>
  <thead>
  <tr>
    <th>Nazwa Zadania</th>
    <th>Wynik</th>
  </tr>
  </thead>
  <tbody>
  <% @tsks.each do |game| %>
      <tr>
        <td><%= game.task.title %></td>
        <td><%= game.points %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= form_tag games_path, :method => "post"  do %>
    <%= hidden_field_tag 'lgt' %>
    <%= hidden_field_tag 'log' %>
    <%= hidden_field_tag 'acr' %>
    <%= hidden_field_tag 'nick', @done_game.session.name %>
    <%= submit_tag "Zagra w inną gry", id: 'sbmt',  class: "btn btn-primary" %>
<% end %>
<script>
    wlmcjs();
</script>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.desc %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Wybierz jedną z gier</h1>
<table>
  <thead>
  <tr>
    <th>Nazwa gry</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= link_to 'Graj', game.tasks.first %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>