config/routes.rb
Rails.application.routes.draw do
  get 'gps', to: 'test#index', as: 'gps'
  controller :tasks do
    post 'tasks/:id' => :answer
  end
  resources :tasks

  controller :games do
    get 'games' => :index
    post 'games' => :show
    get '/games/:id', to: 'games#end', as: 'gameend'
  end
  resources :done_tasks

  resources :done_games
  resources :sessions
  root 'welcome#index'
end

app/models/done_task.rb
class DoneTask < ActiveRecord::Base
  belongs_to :donegame
  belongs_to :task
  belongs_to :session
end

app/controllers/done_tasks_controller.rb
class DoneTasksController < ApplicationController
  before_action :set_done_task, only: [:show, :edit, :update, :destroy]

  # GET /done_tasks
  # GET /done_tasks.json
  def index
    @done_tasks = DoneTask.all
  end

  # GET /done_tasks/1
  # GET /done_tasks/1.json
  def show
  end

  # GET /done_tasks/new
  def new
    @done_task = DoneTask.new
  end

  # GET /done_tasks/1/edit
  def edit
  end

  # POST /done_tasks
  # POST /done_tasks.json
  def create
    @done_task = DoneTask.new(done_task_params)

    respond_to do |format|
      if @done_task.save
        format.html { redirect_to @done_task, notice: 'Done task was successfully created.' }
        format.json { render :show, status: :created, location: @done_task }
      else
        format.html { render :new }
        format.json { render json: @done_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /done_tasks/1
  # PATCH/PUT /done_tasks/1.json
  def update
    respond_to do |format|
      if @done_task.update(done_task_params)
        format.html { redirect_to @done_task, notice: 'Done task was successfully updated.' }
        format.json { render :show, status: :ok, location: @done_task }
      else
        format.html { render :edit }
        format.json { render json: @done_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /done_tasks/1
  # DELETE /done_tasks/1.json
  def destroy
    @done_task.destroy
    respond_to do |format|
      format.html { redirect_to done_tasks_url, notice: 'Done task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_done_task
      @done_task = DoneTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def done_task_params
      params.require(:done_task).permit(:donegame_id, :task_id, :session_id, :result, :endtime)
    end
end

app/helpers/done_tasks_helper.rb
module DoneTasksHelper
end

app/views/done_tasks/_form.html.erb
<%= form_for(@done_task) do |f| %>
  <% if @done_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@done_task.errors.count, "error") %> prohibited this done_task from being saved:</h2>

      <ul>
      <% @done_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :donegame_id %><br>
    <%= f.text_field :donegame_id %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.text_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :session_id %><br>
    <%= f.text_field :session_id %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.number_field :result %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br>
    <%= f.datetime_select :endtime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/done_tasks/edit.html.erb
<h1>Editing done_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @done_task %> |
<%= link_to 'Back', done_tasks_path %>

app/views/done_tasks/index.html.erb
<h1>Listing done_tasks</h1>

<table>
  <thead>
    <tr>
      <th>Donegame</th>
      <th>Task</th>
      <th>Session</th>
      <th>Result</th>
      <th>Endtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @done_tasks.each do |done_task| %>
      <tr>
        <td><%= done_task.donegame %></td>
        <td><%= done_task.task %></td>
        <td><%= done_task.session %></td>
        <td><%= done_task.result %></td>
        <td><%= done_task.endtime %></td>
        <td><%= link_to 'Show', done_task %></td>
        <td><%= link_to 'Edit', edit_done_task_path(done_task) %></td>
        <td><%= link_to 'Destroy', done_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Done task', new_done_task_path %>

app/views/done_tasks/new.html.erb
<h1>New done_task</h1>

<%= render 'form' %>

<%= link_to 'Back', done_tasks_path %>

app/views/done_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Donegame:</strong>
  <%= @done_task.donegame %>
</p>

<p>
  <strong>Task:</strong>
  <%= @done_task.task %>
</p>

<p>
  <strong>Session:</strong>
  <%= @done_task.session %>
</p>

<p>
  <strong>Result:</strong>
  <%= @done_task.result %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @done_task.endtime %>
</p>

<%= link_to 'Edit', edit_done_task_path(@done_task) %> |
<%= link_to 'Back', done_tasks_path %>