config/routes.rb
Rails.application.routes.draw do
  get 'gps', to: 'test#index', as: 'gps'
  controller :tasks do
    post 'tasks/:id' => :answer
  end
  resources :tasks

  controller :games do
    get 'games' => :index
    post 'games' => :show
    get '/games/:id', to: 'games#end', as: 'gameend'
  end
  resources :done_tasks

  resources :done_games
  resources :sessions
  root 'welcome#index'
end

app/models/done_game.rb
class DoneGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :session
  has_many :done_tasks, dependent: :destroy, :foreign_key => :donegame_id
end

app/controllers/done_games_controller.rb
class DoneGamesController < ApplicationController
  before_action :set_done_game, only: [:show, :edit, :update, :destroy]

  # GET /done_games
  # GET /done_games.json
  def index
    @done_games = DoneGame.all
  end

  # GET /done_games/1
  # GET /done_games/1.json
  def show
  end

  # GET /done_games/new
  def new
    @done_game = DoneGame.new
  end

  # GET /done_games/1/edit
  def edit
  end

  # POST /done_games
  # POST /done_games.json
  def create
    @done_game = DoneGame.new(done_game_params)

    respond_to do |format|
      if @done_game.save
        format.html { redirect_to @done_game, notice: 'Done game was successfully created.' }
        format.json { render :show, status: :created, location: @done_game }
      else
        format.html { render :new }
        format.json { render json: @done_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /done_games/1
  # PATCH/PUT /done_games/1.json
  def update
    respond_to do |format|
      if @done_game.update(done_game_params)
        format.html { redirect_to @done_game, notice: 'Done game was successfully updated.' }
        format.json { render :show, status: :ok, location: @done_game }
      else
        format.html { render :edit }
        format.json { render json: @done_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /done_games/1
  # DELETE /done_games/1.json
  def destroy
    @done_game.destroy
    respond_to do |format|
      format.html { redirect_to done_games_url, notice: 'Done game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_done_game
      @done_game = DoneGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def done_game_params
      params.require(:done_game).permit(:result, :endtime, :game_id, :session_id)
    end
end

app/helpers/done_games_helper.rb
module DoneGamesHelper
end

app/views/done_games/_form.html.erb
<%= form_for(@done_game) do |f| %>
  <% if @done_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@done_game.errors.count, "error") %> prohibited this done_game from being saved:</h2>

      <ul>
      <% @done_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :result %><br>
    <%= f.number_field :result %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br>
    <%= f.datetime_select :endtime %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :session_id %><br>
    <%= f.text_field :session_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/done_games/edit.html.erb
<h1>Editing done_game</h1>

<%= render 'form' %>

<%= link_to 'Show', @done_game %> |
<%= link_to 'Back', done_games_path %>

app/views/done_games/index.html.erb
<h1>Listing done_games</h1>

<table>
  <thead>
    <tr>
      <th>Result</th>
      <th>Endtime</th>
      <th>Game</th>
      <th>Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @done_games.each do |done_game| %>
      <tr>
        <td><%= done_game.result %></td>
        <td><%= done_game.endtime %></td>
        <td><%= done_game.game %></td>
        <td><%= done_game.session %></td>
        <td><%= link_to 'Show', done_game %></td>
        <td><%= link_to 'Edit', edit_done_game_path(done_game) %></td>
        <td><%= link_to 'Destroy', done_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Done game', new_done_game_path %>

app/views/done_games/new.html.erb
<h1>New done_game</h1>

<%= render 'form' %>

<%= link_to 'Back', done_games_path %>

app/views/done_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Result:</strong>
  <%= @done_game.result %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @done_game.endtime %>
</p>

<p>
  <strong>Game:</strong>
  <%= @done_game.game %>
</p>

<p>
  <strong>Session:</strong>
  <%= @done_game.session %>
</p>

<%= link_to 'Edit', edit_done_game_path(@done_game) %> |
<%= link_to 'Back', done_games_path %>